# Generated by Django 5.2.15 on 2026-06-26 07:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataResidency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(choices=[('ghana', 'Ghana (Accra DC)'), ('eu-west-2', 'UK / London'), ('eu-west-1', 'Ireland'), ('us-east-1', 'US East (N. Virginia)')], default='ghana', max_length=32)),
                ('data_classification', models.CharField(default='confidential', max_length=64)),
                ('is_backup', models.BooleanField(default=False)),
                ('backup_region', models.CharField(blank=True, choices=[('ghana', 'Ghana (Accra DC)'), ('eu-west-2', 'UK / London'), ('eu-west-1', 'Ireland'), ('us-east-1', 'US East (N. Virginia)')], default='', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residency_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data residencies',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='DPIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_ref', models.CharField(blank=True, help_text='Document ID or file reference', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, help_text='Next annual review due', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('reviewed', 'Reviewed'), ('superseded', 'Superseded')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpia_reviews', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpia_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DPIA',
                'ordering': ['-signed_at'],
            },
        ),
    ]
