# Generated by Django 5.2.15 on 2026-06-24 13:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('app_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('app_id', models.CharField(db_index=True, max_length=100)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'app_id', 'is_revoked'], name='iam_auth_au_user_id_1acb3d_idx'), models.Index(fields=['expires_at'], name='iam_auth_au_expires_baab53_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('authenticated', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=list)),
                ('roles', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('state_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'app_id', 'authenticated'], name='iam_auth_au_user_id_bc3516_idx'), models.Index(fields=['expires_at'], name='iam_auth_au_expires_95332a_idx')],
                'unique_together': {('user', 'app_id')},
            },
        ),
    ]
