# Generated by Django 5.2.15 on 2026-06-22 11:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zitadel_project_id', models.CharField(blank=True, default='', max_length=255)),
                ('zitadel_app_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('client_id_hash', models.CharField(blank=True, default='', max_length=64)),
                ('lifecycle_state', models.CharField(choices=[('onboarding', 'Onboarding'), ('sandbox_validated', 'Sandbox Validated'), ('production_live', 'Production Live'), ('suspended', 'Suspended'), ('decommissioned', 'Decommissioned')], default='onboarding', max_length=30)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('redirect_uris', models.JSONField(blank=True, default=list)),
                ('post_logout_redirect_uris', models.JSONField(blank=True, default=list)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('secret_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_gate_passed', models.BooleanField(default=False)),
                ('granted_system_refs', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients_oidcclient',
                'indexes': [models.Index(fields=['lifecycle_state'], name='clients_oid_lifecyc_6cc3d1_idx')],
            },
        ),
    ]
