# Generated by Django 5.2.15 on 2026-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='system_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
