# Generated by Django 5.2.15 on 2026-06-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_oidcclient_name_oidcclient_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='claim_allow_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
