# Generated by Django 5.2.15 on 2026-06-22 11:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zitadel_user_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('user_type', models.CharField(choices=[('staff', 'Staff'), ('board', 'Board Member'), ('nbec', 'NBEC'), ('student', 'Student'), ('external', 'External'), ('public', 'Public')], db_index=True, default='external', max_length=20)),
                ('status', models.CharField(choices=[('pre_active', 'Pre-Active'), ('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending')], db_index=True, default='pre_active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('hrms_event_ref', models.CharField(blank=True, default='', max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='ZitadelUserSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zitadel_resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=50)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zitadel_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_zitadel_sync',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'status'], name='accounts_us_user_ty_e34060_idx'),
        ),
    ]
