# Generated by Django 5.2.15 on 2026-06-24 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('system_code', models.CharField(db_index=True, max_length=50)),
                ('zitadel_user_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('role_ids', models.JSONField(blank=True, default=list)),
                ('as_admin', models.BooleanField(default=False)),
                ('token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_invitation',
                'indexes': [models.Index(fields=['email', 'status'], name='accounts_in_email_0582fe_idx'), models.Index(fields=['system_code', 'status'], name='accounts_in_system__9b0754_idx')],
            },
        ),
    ]
