# Generated by Django 5.2.15 on 2026-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_first_name_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='lookup_token_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
