# Generated by Django 5.2.15 on 2026-06-22 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainAnchor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.BigIntegerField(unique=True)),
                ('hash_chain_ref', models.CharField(db_index=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('anchored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_chainanchor',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user_id', models.UUIDField(db_index=True)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('channel', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(blank=True, default='success', max_length=50)),
                ('redacted_metadata', models.JSONField(blank=True, default=dict)),
                ('hash_chain_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_auditevent',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor_user_id', 'timestamp'], name='audit_audit_actor_u_1a4ec4_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['channel', 'timestamp'], name='audit_audit_channel_7660a4_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_d7f04a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('kind', models.CharField(default='oidc', max_length=50)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('claims_hash', models.CharField(blank=True, default='', max_length=64)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_activesession',
                'indexes': [models.Index(fields=['user', 'revoked'], name='audit_activ_user_id_b7ea3d_idx'), models.Index(fields=['jti'], name='audit_activ_jti_9d9bcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=1024)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entries', to='audit.auditevent')),
            ],
            options={
                'db_table': 'audit_outbox',
                'indexes': [models.Index(fields=['delivered', 'next_retry_at'], name='audit_outbo_deliver_ec1247_idx')],
            },
        ),
    ]
