# Generated by Django 5.2.15 on 2026-06-22 11:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('severity', models.CharField(default='medium', max_length=50)),
                ('predicate_json', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_ruledefinition',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_code', models.CharField(db_index=True, max_length=100)),
                ('role_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('permission_strings', models.JSONField(blank=True, default=list)),
                ('version', models.IntegerField(default=1)),
                ('owner_system', models.CharField(blank=True, default='', max_length=100)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_role',
                'indexes': [models.Index(fields=['system_code', 'is_deprecated'], name='rbac_role_system__ea7e0c_idx')],
                'unique_together': {('system_code', 'role_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RoleBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('effective', 'Effective'), ('revoked', 'Revoked')], db_index=True, default='requested', max_length=20)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bindings', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_rolebinding',
                'indexes': [models.Index(fields=['user', 'state'], name='rbac_rolebi_user_id_04e83c_idx'), models.Index(fields=['role', 'state'], name='rbac_rolebi_role_id_080890_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zitadel_claim_key', models.CharField(max_length=255)),
                ('zitadel_claim_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='rbac.role')),
            ],
            options={
                'db_table': 'rbac_roleclaim',
                'unique_together': {('role', 'zitadel_claim_key')},
            },
        ),
    ]
