# Generated by Django 5.2.15 on 2026-06-24 21:58
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_role_is_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(db_index=True, max_length=20)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], db_index=True, default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_report_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_access_review_campaign',
            },
        ),
        migrations.CreateModel(
            name='AccessReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_code', models.CharField(max_length=50)),
                ('role_id', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('keep', 'Keep'), ('revoke', 'Revoke'), ('change_role', 'Change role')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='rbac.rolebinding')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rbac.accessreviewcampaign')),
                ('new_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rbac.role')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_items', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_access_review_item',
                'indexes': [models.Index(fields=['campaign', 'decision'], name='rbac_access_campaig_d7558f_idx')],
            },
        ),
    ]
