# Generated by Django 5.2.15 on 2026-06-22 11:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('target_host', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_uri', models.URLField(blank=True, default='', max_length=1024)),
                ('recording_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('vault_lease_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pam_pamsession',
                'indexes': [models.Index(fields=['user', 'status'], name='pam_pamsess_user_id_2d5f3e_idx')],
            },
        ),
    ]
