#!/usr/bin/env python3
"""Bootstrap Zitadel with project, OIDC app, and service account.

Run after Zitadel is healthy:

    docker compose exec django python scripts/bootstrap_zitadel.py

Reads the machine key generated by Zitadel during first start-from-init,
authenticates via JWT bearer grant, and creates:

  1. "IAM 3.0" project
  2. "IAM SPA" OIDC application (PKCE, authorization_code + refresh_token)
  3. "iam-backend" service account (machine user) with a PAT

Outputs the env vars needed by the Django backend.
"""

import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import jwt
import requests
from cryptography.hazmat.primitives import serialization

ZITADEL_HOST = os.getenv("ZITADEL_INTERNAL_HOST", os.getenv("ZITADEL_HOST", "http://zitadel:8080"))
MACHINE_KEY_PATH = Path(os.getenv("ZITADEL_MACHINE_KEY_PATH", "/machinekey/zitadel-admin-sa.json"))
ISSUER = f"{ZITADEL_HOST.rstrip('/')}"

# Zitadel's ExternalDomain is "localhost" in dev — we use a custom adapter
# to send `Host: localhost:8080` so Zitadel resolves the instance correctly.
ZITADEL_EXTERNAL_DOMAIN = "localhost:8080"


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


class _HostHeaderAdapter(requests.adapters.HTTPAdapter):
    def __init__(self, host_header: str, **kwargs):
        self._host = host_header
        super().__init__(**kwargs)

    def add_headers(self, request, **kwargs):
        request.headers["Host"] = self._host


def _session() -> requests.Session:
    s = requests.Session()
    s.mount("http://", _HostHeaderAdapter(ZITADEL_EXTERNAL_DOMAIN))
    s.mount("https://", _HostHeaderAdapter(ZITADEL_EXTERNAL_DOMAIN))
    return s


# ---------------------------------------------------------------------------
# Step 1 — Wait for Zitadel
# ---------------------------------------------------------------------------

def wait_for_zitadel(timeout: int = 180) -> None:
    session = _session()
    url = f"{ISSUER}/debug/healthz"
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            resp = session.get(url, timeout=5)
            if resp.status_code == 200:
                print("Zitadel is healthy.")
                return
        except requests.RequestException:
            pass
        print("Waiting for Zitadel to become healthy …")
        time.sleep(3)
    die("Zitadel did not become healthy within timeout.")


# ---------------------------------------------------------------------------
# Step 2 — Load machine key & get access token (JWT bearer)
# ---------------------------------------------------------------------------

def load_machine_key() -> dict:
    if not MACHINE_KEY_PATH.exists():
        die(
            f"Machine key not found at {MACHINE_KEY_PATH}. "
            "Run `docker compose up -d` first and wait for Zitadel setup to complete."
        )
    with open(MACHINE_KEY_PATH) as f:
        return json.load(f)


def get_access_token(key_data: dict) -> str:
    private_key = serialization.load_pem_private_key(
        key_data["key"].encode(), password=None
    )

    now = datetime.now(timezone.utc)
    payload = {
        "iss": key_data["userId"],
        "sub": key_data["userId"],
        "aud": f"http://{ZITADEL_EXTERNAL_DOMAIN}",
        "iat": now,
        "exp": now + timedelta(hours=1),
    }
    assertion = jwt.encode(
        payload, private_key, algorithm="RS256", headers={"kid": key_data["keyId"]}
    )

    session = _session()
    resp = session.post(
        f"{ISSUER}/oauth/v2/token",
        data={
            "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
            "assertion": assertion,
            "scope": "openid profile urn:zitadel:iam:org:project:id:zitadel:aud",
        },
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Token exchange failed ({resp.status_code}): {resp.text}")
    return resp.json()["access_token"]


# ---------------------------------------------------------------------------
# Step 3 — Get default org
# ---------------------------------------------------------------------------

def get_org_id(token: str) -> str:
    session = _session()
    resp = session.get(
        f"{ISSUER}/management/v1/orgs/me",
        headers={"Authorization": f"Bearer {token}"},
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to get org ({resp.status_code}): {resp.text}")
    return resp.json()["org"]["id"]


# ---------------------------------------------------------------------------
# Step 4 — Create project
# ---------------------------------------------------------------------------

def create_project(token: str, org_id: str) -> str:
    session = _session()
    resp = session.post(
        f"{ISSUER}/management/v1/projects",
        json={"name": "IAM 3.0"},
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create project ({resp.status_code}): {resp.text}")
    project_id = resp.json()["id"]
    print(f"Created project: IAM 3.0  (id={project_id})")
    return project_id


# ---------------------------------------------------------------------------
# Step 5 — Create OIDC application
# ---------------------------------------------------------------------------

def create_oidc_app(token: str, project_id: str) -> dict:
    payload = {
        "name": "IAM SPA",
        "redirectUris": [
            "http://localhost:5173/login/callback",
            "http://localhost:8000/login/callback",
        ],
        "postLogoutRedirectUris": [
            "http://localhost:5173/login",
            "http://localhost:8000/login",
        ],
        "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
        "grantTypes": [
            "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
            "OIDC_GRANT_TYPE_REFRESH_TOKEN",
        ],
        "appType": "OIDC_APP_TYPE_USER_AGENT",
        "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
        "version": "OIDC_VERSION_1_0",
        "devMode": True,
        "accessTokenType": "OIDC_TOKEN_TYPE_JWT",
    }
    session = _session()
    resp = session.post(
        f"{ISSUER}/management/v1/projects/{project_id}/apps/oidc",
        json=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create OIDC app ({resp.status_code}): {resp.text}")
    data = resp.json()
    client_id = data.get("clientId", "")
    print(f"Created OIDC app: IAM SPA  (client_id={client_id})")
    return {
        "client_id": client_id,
        "client_secret": "",
    }


# ---------------------------------------------------------------------------
# Step 6 — Create service account (machine user) with machine key
# ---------------------------------------------------------------------------

def create_service_account(token: str, org_id: str) -> str:
    session = _session()
    resp = session.post(
        f"{ISSUER}/management/v1/users/machine",
        json={
            "userName": "iam-backend",
            "name": "IAM Backend Service Account",
            "description": "Django IAM backend Zitadel sync",
        },
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create service account ({resp.status_code}): {resp.text}")
    user_id = resp.json()["userId"]
    print(f"Created service account: iam-backend  (id={user_id})")

    resp = session.post(
        f"{ISSUER}/management/v1/users/{user_id}/keys",
        json={
            "type": "KEY_TYPE_JSON",
            "expirationDate": (datetime.now(timezone.utc) + timedelta(days=365)).isoformat(),
        },
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create machine key ({resp.status_code}): {resp.text}")
    key_details_b64 = resp.json().get("keyDetails", "")
    if not key_details_b64:
        die("No keyDetails in response")
    import base64
    key_json = base64.b64decode(key_details_b64).decode()
    print("Generated machine key for service account.")
    return key_json


# ---------------------------------------------------------------------------
# Step 7 — Create the login-client service user with PAT for Login V2
# ---------------------------------------------------------------------------

LOGIN_CLIENT_PAT_PATH = "/machinekey/login-client.pat"


def setup_login_client(token: str, org_id: str) -> str:
    """Create the login-client machine user with a PAT, grant ORG_OWNER, write PAT to disk."""
    session = _session()

    # Search for existing login-client first
    resp = session.post(
        f"{ISSUER}/management/v1/users/_search",
        json={
            "query": {"offset": "0", "limit": 100, "asc": True},
            "queries": [{
                "userNameQuery": {
                    "userName": "login-client",
                    "method": "USER_NAME_QUERY_METHOD_EQUALS",
                }
            }],
        },
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to search for login-client ({resp.status_code}): {resp.text}")

    existing = resp.json().get("result", [])
    if existing:
        login_client_id = existing[0]["id"]
        print(f"Login-client user already exists: {login_client_id}")
    else:
        resp = session.post(
            f"{ISSUER}/management/v1/users/machine",
            json={
                "userName": "login-client",
                "name": "IAM Login Client",
                "description": "Login V2 service user for OIDC flow authentication",
            },
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            timeout=15,
        )
        if resp.status_code != 200:
            die(f"Failed to create login-client user ({resp.status_code}): {resp.text}")
        login_client_id = resp.json()["userId"]
        print(f"Created login-client user: {login_client_id}")

    # Create a PAT for the login-client
    resp = session.post(
        f"{ISSUER}/management/v1/users/{login_client_id}/pats",
        json={"expirationDate": "2040-01-01T00:00:00Z"},
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create PAT for login-client ({resp.status_code}): {resp.text}")

    pat_token = resp.json().get("token", "")
    if not pat_token:
        die("No PAT token in response")

    # Write PAT to the file the login container expects
    pat_path = Path(LOGIN_CLIENT_PAT_PATH)
    pat_path.parent.mkdir(parents=True, exist_ok=True)
    pat_path.write_text(pat_token)
    print(f"Written PAT to {pat_path} ({len(pat_token)} chars)")

    # Grant ORG_OWNER role
    resp = session.post(
        f"{ISSUER}/management/v1/orgs/me/members",
        json={"userId": login_client_id, "roles": ["ORG_OWNER"]},
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code == 200:
        print("Granted ORG_OWNER role to login-client user.")
    elif resp.status_code == 409:
        print("login-client is already an org member.")
    else:
        die(f"Failed to add login-client as org member ({resp.status_code}): {resp.text}")

    return login_client_id


# ---------------------------------------------------------------------------
# Step 8 — Create AMS OIDC application
# ---------------------------------------------------------------------------

def create_ams_app(token: str, project_id: str) -> dict:
    session = _session()
    # Check if AMS app already exists
    resp = session.get(
        f"{ISSUER}/management/v1/projects/{project_id}/apps",
        headers={"Authorization": f"Bearer {token}"},
        timeout=15,
    )
    if resp.status_code == 200:
        for app in resp.json().get("result", []):
            if app.get("appName") == "AMS":
                print(f"AMS OIDC app already exists  (client_id={app.get('clientId', '')})")
                return {"client_id": app.get("clientId", ""), "client_secret": ""}

    payload = {
        "name": "AMS",
        "redirectUris": [
            "http://localhost:5173/login/callback",
            "http://localhost:5173/auth/callback",
        ],
        "postLogoutRedirectUris": [
            "http://localhost:5173/login",
            "http://localhost:5173",
        ],
        "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
        "grantTypes": [
            "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
            "OIDC_GRANT_TYPE_REFRESH_TOKEN",
        ],
        "appType": "OIDC_APP_TYPE_USER_AGENT",
        "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
        "version": "OIDC_VERSION_1_0",
        "devMode": True,
        "accessTokenType": "OIDC_TOKEN_TYPE_JWT",
    }
    resp = session.post(
        f"{ISSUER}/management/v1/projects/{project_id}/apps/oidc",
        json=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create AMS OIDC app ({resp.status_code}): {resp.text}")
    data = resp.json()
    client_id = data.get("clientId", "")
    print(f"Created OIDC app: AMS  (client_id={client_id})")
    return {
        "client_id": client_id,
        "client_secret": "",
    }


# ---------------------------------------------------------------------------
# Step 9 — Create NBES OIDC application
# ---------------------------------------------------------------------------

def create_nbes_app(token: str, project_id: str) -> dict:
    session = _session()
    resp = session.get(
        f"{ISSUER}/management/v1/projects/{project_id}/apps",
        headers={"Authorization": f"Bearer {token}"},
        timeout=15,
    )
    if resp.status_code == 200:
        for app in resp.json().get("result", []):
            if app.get("appName") == "NBES":
                print(f"NBES OIDC app already exists  (client_id={app.get('clientId', '')})")
                return {"client_id": app.get("clientId", ""), "client_secret": ""}

    payload = {
        "name": "NBES",
        "redirectUris": [
            "http://localhost:5174/login/callback",
            "http://localhost:5174/auth/callback",
        ],
        "postLogoutRedirectUris": [
            "http://localhost:5174/login",
            "http://localhost:5174",
        ],
        "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
        "grantTypes": [
            "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
            "OIDC_GRANT_TYPE_REFRESH_TOKEN",
        ],
        "appType": "OIDC_APP_TYPE_USER_AGENT",
        "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
        "version": "OIDC_VERSION_1_0",
        "devMode": True,
        "accessTokenType": "OIDC_TOKEN_TYPE_JWT",
    }
    resp = session.post(
        f"{ISSUER}/management/v1/projects/{project_id}/apps/oidc",
        json=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code != 200:
        die(f"Failed to create NBES OIDC app ({resp.status_code}): {resp.text}")
    data = resp.json()
    client_id = data.get("clientId", "")
    print(f"Created OIDC app: NBES  (client_id={client_id})")
    return {
        "client_id": client_id,
        "client_secret": "",
    }


def grant_login_client_role(token: str, user_id: str) -> None:
    """Grant the instance-level IAM_LOGIN_CLIENT role.

    The Login V2 app authenticates to Zitadel as this user and calls the
    `/v2/oidc/auth_requests` API to finalise the OIDC flow and obtain the
    callback URL that redirects the browser back to the client app. That API
    requires the dedicated `IAM_LOGIN_CLIENT` role — `IAM_OWNER` is NOT
    sufficient and the call returns 403 (AUTH-AWfge) without it, which leaves
    the user stuck on the login page after a successful sign-in.
    """
    session = _session()
    # The user is already an instance member (IAM_OWNER) from init, so update
    # the membership to add the role; fall back to creating it if missing.
    resp = session.put(
        f"{ISSUER}/admin/v1/members/{user_id}",
        json={"roles": ["IAM_OWNER", "IAM_LOGIN_CLIENT"]},
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code == 200:
        print("Granted IAM_LOGIN_CLIENT instance role to login service user.")
        return
    resp = session.post(
        f"{ISSUER}/admin/v1/members",
        json={"userId": user_id, "roles": ["IAM_LOGIN_CLIENT"]},
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    if resp.status_code in (200, 409):
        print("Granted IAM_LOGIN_CLIENT instance role to login service user.")
    else:
        die(f"Failed to grant IAM_LOGIN_CLIENT ({resp.status_code}): {resp.text}")


if __name__ == "__main__":
    wait_for_zitadel()

    key_data = load_machine_key()
    print(f"Loaded machine key for user: {key_data.get('userId', 'unknown')}")

    token = get_access_token(key_data)
    print("Authenticated via JWT bearer grant.")

    org_id = get_org_id(token)
    print(f"Default org id: {org_id}")

    project_id = create_project(token, org_id)
    oidc = create_oidc_app(token, project_id)
    ams = create_ams_app(token, project_id)
    nbes = create_nbes_app(token, project_id)
    sa_key_json = create_service_account(token, org_id)
    setup_login_client(token, org_id)
    grant_login_client_role(token, key_data["userId"])

    # Enforce mandatory MFA and enable the supported second factors.
    try:
        import configure_mfa
        configure_mfa.main()
    except Exception as exc:  # noqa: BLE001 - bootstrap should not hard-fail on this
        print(f"WARN: MFA configuration step failed: {exc}")

    # Point ZITADEL at the dev SMTP sink (Mailpit) so invite emails send.
    try:
        import configure_smtp
        configure_smtp.main()
    except Exception as exc:  # noqa: BLE001
        print(f"WARN: SMTP configuration step failed: {exc}")

    print("\nNext: provision per-system projects/roles and the OIDCClient mirror:")
    print("  docker compose exec django python manage.py setup_systems")

    # Restart login container so it picks up the PAT file
    import subprocess
    subprocess.run(
        ["docker", "compose", "restart", "login"],
        capture_output=True,
        timeout=30,
    )
    print("Restarted login container with new PAT.")

    print("\n" + "=" * 60)
    print("  Bootstrap complete! Add these to .env:")
    print("=" * 60)
    print(f"  ZITADEL_HOST={ZITADEL_HOST}")
    print(f"  ZITADEL_PROJECT_ID={project_id}")
    print(f"  ZITADEL_ORG_ID={org_id}")
    print(f"  ZITADEL_SERVICE_ACCOUNT_JWT={sa_key_json}")
    print(f"  OIDC_RP_CLIENT_ID={oidc['client_id']}")
    print(f"  OIDC_RP_CLIENT_SECRET={oidc.get('client_secret', '')}")
    print(f"  AMS_CLIENT_ID={ams['client_id']}")
    print(f"  NBES_CLIENT_ID={nbes['client_id']}")
    print("=" * 60)
