# Generated by Django 5.2.15 on 2026-06-26 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrmsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('hrms.joiner', 'Joiner'), ('hrms.mover', 'Mover'), ('hrms.leaver', 'Leaver')], db_index=True, max_length=32)),
                ('target_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('payload', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('resolved', 'Resolved')], db_index=True, default='received', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_hrms_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', 'event_type'], name='lifecycle_h_status_6f11a5_idx')],
            },
        ),
    ]
